local _, t = ...

-- Venoxis Discord Blocklist Table

t.version = "@project-version@"

t.case_table = {
  [1] = {
    name = "Alcyona",
    faction = "Horde",
    class = "PALADIN",
    category = "trade",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [2] = {
    name = "Alle",
    faction = "Horde",
    category = "raid",
    description = "Veranstaltet als Gilde BT Prio Runs und scamt hart bei der Lootvergabe (Randoms dürfen nur auf ihre Prios rollen aber Gilde darf auf alles Bieten und Prios überschreiben.",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [3] = {
    name = "Alonewoolf",
    faction = "Horde",
    class = "DRUID",
    category = "dungeon",
    description = "Stellt im 5er vor dem Endboss den PM ein und Ninjat fast alles / bisher 3 Meldungen zu diesem Spieler",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [4] = {
    name = "Arbeitslos",
    faction = "Horde",
    class = "MAGE",
    category = "trade",
    description = "Bekommt vom RL ein Item falsch zugewiesen und geht nach der Aufforderung dieses zu traden direkt offline",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [5] = {
    name = "Boomboompøw",
    faction = "Horde",
    category = "raid",
    description = "Scamt Prio1 Item und vergibt es an ein Gildenmitglied (Mainchar = Nøxic)",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [6] = {
    name = "Brodyrich",
    faction = "Horde",
    class = "DEATHKNIGHT",
    category = "gdkp",
    description = "Geht mit 75k vom Gdkp offline und kickt alle vom DC-Server / Dc-Tag = Gigawizard#8360",
    level = 4,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [7] = {
    name = "Cradran",
    faction = "Horde",
    class = "WARLOCK",
    category = "trade",
    description = "Rollt gern ohne zu Zahlen",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [8] = {
    name = "Cruzitô",
    faction = "Horde",
    class = "MAGE",
    category = "trade",
    description = "Steckt gern Items sich selbst oder seinen Kumpels zu. ",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [9] = {
    name = "Dakiny",
    faction = "Alliance",
    class = "PALADIN",
    category = "raid",
    description = "Kara Mount geninjat + leave",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [10] = {
    name = "Dannymage",
    faction = "Horde",
    class = "MAGE",
    category = "gdkp",
    description = "Eröffnet Gdkp run und haut dann mit dem gesamten Pot ab. 81.402 Gold / Siehe auch Charakter: Pumperlumper",
    level = 4,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [11] = {
    name = "Danser ",
    faction = "Horde",
    class = "ROGUE",
    category = "raid",
    description = "Danser und Intonraiha ninjan sich gern mal gegenseitig Items zu als Plündermeister. Scam Pugs!",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [12] = {
    name = "Daserus",
    faction = "Horde",
    class = "PALADIN",
    category = "gdkp",
    description = "Geheime Absprachen bezüglich Gold-Gebote in seinen Gdkp-Raids (sein Twink heißt Fleta)",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [13] = {
    name = "Deinorc",
    faction = "Horde",
    class = "WARRIOR",
    category = "raid",
    description = "Ninjat durch PM-Bug das Prio1 Item eines anderen Spielers und geht instant offline",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [14] = {
    name = "Diggernick",
    faction = "Horde",
    category = "trade",
    description = "Rollt gern ohne zu Zahlen",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [15] = {
    name = "Dirtyrouge",
    faction = "Horde",
    class = "ROGUE",
    category = "trade",
    description = "Lootdrama / spricht kein Deutsch / versucht zu scammen",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [16] = {
    name = "Dreamyx",
    faction = "Horde",
    class = "SHAMAN",
    category = "gdkp",
    description = "ZA GDKP Orga: Will loot behalten statt diss aber nicht zahlen. Geht off vorm Endboss mitm Pot",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [17] = {
    name = "Elrether",
    faction = "Horde",
    class = "MAGE",
    category = "dungeon",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [18] = {
    name = "Faktorial",
    faction = "Horde",
    class = "MAGE",
    category = "dungeon",
    description = "Kassiert 120 Gold - pullt - stirbt und geht dann offline ",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [19] = {
    name = "Fikky",
    faction = "Horde",
    category = "gdkp",
    description = "Blacklisted sich selbst: Verkauft ZA Bär für 2K und fügt es nicht dem GDKP Pot hinzu.",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [20] = {
    name = "Fleta",
    faction = "Horde",
    class = "WARRIOR",
    category = "gdkp",
    description = "Geheime Absprachen bezüglich Gold-Gebote in seinen Gdkp-Raids (sein Main heißt Daserus)",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [21] = {
    name = "Fyfy",
    faction = "Horde",
    class = "DRUID",
    category = "dungeon",
    description = "Needet alle Items in 5mann HC+ ",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [22] = {
    name = "Greves",
    faction = "Horde",
    category = "gdkp",
    description = "ZA GDKP Orga: Will loot behalten statt diss aber nicht zahlen.",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [23] = {
    name = "Gromgrul",
    faction = "Horde",
    category = "trade",
    description = "Plündert gern mal die Gildenbank",
    level = 4,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [24] = {
    name = "Handwerkerr",
    faction = "Horde",
    category = "gdkp",
    description = "GDKP Betrüger / vorheriger Name war: Würfelbotqt / unterschlägt 116k Gold und zahlt keinen Cut aus",
    level = 4,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [25] = {
    name = "Hellsângel",
    faction = "Horde",
    category = "gdkp",
    description = "Geht mit 23.5k vom Gdkp offline und kommt nicht wieder",
    level = 4,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [26] = {
    name = "Hoibedere",
    faction = "Horde",
    class = "PALADIN",
    category = "raid",
    description = "Gönnt sich als ZA alle Splitter Greens und Hexerstecken",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [27] = {
    name = "Intonraiha",
    faction = "Horde",
    class = "PALADIN",
    category = "raid",
    description = "Danser und Intonraiha ninjan sich gern mal gegenseitig Items zu als Plündermeister. Scam Pugs!",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [28] = {
    name = "Javoor",
    faction = "Horde",
    class = "DRUID",
    category = "trade",
    description = "Rollt gern ohne zu Zahlen",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [29] = {
    name = "Jenpai",
    faction = "Horde",
    category = "dungeon",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [30] = {
    name = "Jensha",
    faction = "Horde",
    class = "MAGE",
    category = "dungeon",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [31] = {
    name = "Kessler",
    faction = "Horde",
    class = "DRUID",
    category = "raid",
    description = "Hält sich nicht an Prio-Listen und verteilt Items nach seinem Ermessen",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [32] = {
    name = "Kugit",
    faction = "Horde",
    class = "Jäger",
    category = "raid",
    description = "Erstellt NaxxPUG ohne Lootsystem und tradet Endbossloot an jemanden der nicht per Roll gewonnen hat",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [33] = {
    name = "Lachman",
    faction = "Horde",
    class = "WARRIOR",
    category = "raid",
    description = "Ninjat Items als Plündermeister",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [34] = {
    name = "Laredai",
    faction = "Horde",
    class = "Priester",
    category = "raid",
    description = "Lockt Betrayer aber gibt diese Info nicht an nachträglich in den Raid geladene Spieler weiter. Nachzügler setzt Betrayer auf Prio1 - erhält trotzdem keine Info / Betrayer ist droppt und wurde an Stahlklang-Gildenmember vergeben",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [35] = {
    name = "Lebkuchen",
    faction = "Horde",
    class = "SHAMAN",
    category = "raid",
    description = "Locken mitten im ZA Prio Run Items",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [36] = {
    name = "Lil Toxec",
    faction = "Horde",
    category = "harassment",
    description = "Geht als Buyer mit und hat kein Gold - beleidigt dann nach Aufforderung zu kaufen.",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [37] = {
    name = "Lister",
    faction = "Horde",
    class = "MAGE",
    category = "dungeon",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [38] = {
    name = "Lookìí",
    faction = "Horde",
    class = "DRUID",
    category = "raid",
    description = "Verrollt Items nicht - zieht sie einfach an / lässt Items im Raid ablaufen - sodass kein verrollen mehr möglich ist / DC-Tag: Lookii#9050",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [39] = {
    name = "Lovetap",
    faction = "Horde",
    class = "SHAMAN",
    category = "harassment",
    description = "Antisemit",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [40] = {
    name = "Lyzak",
    faction = "Horde",
    class = "PALADIN",
    category = "raid",
    description = "Kassiert 2k Gold als Eintrittsgeld für 25Prio-Run + scamt dann Prio1 Item Turning Tide / Empfänger des Items: Lorani - gleiche Gilde / Discord-Tag: EinfachCanTV#8479",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [41] = {
    name = "Mczwuggi",
    faction = "Horde",
    class = "WARRIOR",
    category = "gdkp",
    description = "Steckt kompletten Pot im 10er GDKP ein. Scam",
    level = 4,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [42] = {
    name = "Melthise",
    faction = "Horde",
    class = "MAGE",
    category = "dungeon",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [43] = {
    name = "Nakrotss",
    faction = "Horde",
    class = "MAGE",
    category = "dungeon",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [44] = {
    name = "Niemandmc",
    faction = "Horde",
    class = "WARRIOR",
    category = "raid",
    description = "Ninjat weil PM vergessen wurde und verkauft die Tokens",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [45] = {
    name = "Nøxic",
    faction = "Horde",
    class = "Priester",
    category = "raid",
    description = "Scamt Prio1 Item und vergibt es an ein Gildenmitglied / Twink = Boomboompøw",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [46] = {
    name = "Palaslust",
    faction = "Horde",
    class = "PALADIN",
    category = "raid",
    description = "Prio 1 Run: Der RL teilt das Sartharion-3D-Mount dem falschen Spieler zu und dieser geht instant offline. ",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [47] = {
    name = "PPQOR",
    faction = "Horde",
    class = "MAGE",
    category = "dungeon",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [48] = {
    name = "Pumperlumper",
    faction = "Horde",
    class = "MAGE",
    category = "gdkp",
    description = "Eröffnet Gdkp run und haut dann mit dem gesamten Pot ab. 81.402 Gold / Namechange zu: Dannymage",
    level = 4,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [49] = {
    name = "Rôôz",
    faction = "Horde",
    class = "WARRIOR",
    category = "harassment",
    description = "Geht als Buyer mit und hat kein Gold - beleidigt dann nach Aufforderung zu kaufen.",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [50] = {
    name = "Sandmanncs",
    faction = "Horde",
    class = "MAGE",
    category = "gdkp",
    description = "Schließt Raider willkürlich vom Cut aus DC-Tag: Sandmann#7274",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [51] = {
    name = "Saucenbinder",
    faction = "Horde",
    category = "trade",
    description = "Plündert gern mal die Gildenbank",
    level = 4,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [52] = {
    name = "Sintussa",
    faction = "Horde",
    class = "WARRIOR",
    category = "gdkp",
    description = "Kickt rnd Leute aus dem GDKP und zwingt zum kauf von Trashitems",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [53] = {
    name = "Strønghøld",
    faction = "Horde",
    class = "WARRIOR",
    category = "raid",
    description = "Ändert im Priorun die Prios ab nachdem die Liste veröffentlich wurde (wieder hidden und reopen). Gilde steht dahinter ... komplett meiden den Verein.",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [54] = {
    name = "Stysthy",
    faction = "Horde",
    class = "DEATHKNIGHT",
    category = "raid",
    description = "Würfelt 2x für ein Item bei Malygos. Der RL übersieht das und weist ihm ungerechtfertigt ein Item zu. Danach verlässt er direkt den Raid. Wurde wegen diesem Vorfall aus der Gilde gekickt.",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [55] = {
    name = "Sunnytätär",
    faction = "Horde",
    category = "raid",
    description = "Locken mitten im ZA Prio Run Items",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [56] = {
    name = "Thilon",
    faction = "Horde",
    class = "PALADIN",
    category = "raid",
    description = "Lockt Betrayer aber gibt diese Info nicht an nachträglich in den Raid geladene Spieler weiter. Nachzügler setzt Betrayer auf Prio1 - erhält trotzdem keine Info / Betrayer ist droppt und wurde an Stahlklang-Gildenmember vergeben",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [57] = {
    name = "Trytofly",
    faction = "Horde",
    category = "trade",
    description = "Scammer! Klaut Craftmats",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [58] = {
    name = "Ukrgul",
    faction = "Horde",
    class = "MAGE",
    category = "dungeon",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [59] = {
    name = "Ultraboost",
    faction = "Horde",
    class = "MAGE",
    category = "gdkp",
    description = "Zahlt falschen Cut aus und beleidigt auf Nachfrage",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [60] = {
    name = "Ungeiimpfter",
    faction = "Horde",
    category = "trade",
    description = "Plündert gern mal die Gildenbank Alts: Dejox(Rogue) / Dkgoesbrbr(DK obv) / Buyvet (Paladin).",
    level = 4,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [61] = {
    name = "Valentinmlk",
    faction = "Horde",
    class = "MAGE",
    category = "dungeon",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [62] = {
    name = "Vejrekaiah",
    faction = "Horde",
    class = "MAGE",
    category = "gdkp",
    description = "Macht Gdkp auf und verschwindet mit dem ganzen Pot / 108.750 Gold",
    level = 4,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [63] = {
    name = "Vibecheckk",
    faction = "Horde",
    category = "raid",
    description = "Lockt rnd Items ohne Vorabinfo",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [64] = {
    name = "Wandan",
    faction = "Horde",
    class = "MAGE",
    category = "dungeon",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [65] = {
    name = "Wortalmombat",
    faction = "Horde",
    category = "harassment",
    description = "Beleidigt aufs übelste den Gildenlead nach Kick (Homophob diesdas)",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [66] = {
    name = "Würfelbotqt",
    faction = "Horde",
    category = "gdkp",
    description = "Geht mit 116k Gold offline und verteilt keinen Cut / GDKP Betrüger / hat Namen in Handwerkerr geändert",
    level = 4,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [67] = {
    name = "Zizmo",
    faction = "Horde",
    class = "HUNTER",
    category = "trade",
    description = "Scammed bei Deathrolls (rolled /2-2 und so faxen) der Frechfuchs",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  [68] = {
    name = "Zullser",
    faction = "Horde",
    class = "MAGE",
    category = "dungeon",
    description = "Booster kickt Leute / geht Offline nach Bezahlung ohne Leistung",
    level = 3,
    url = "https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0",
  },
  --=========================================================================================
  -- End of existing player data import that were listed on the venoxis discord blacklist google sheet:
  -- https://docs.google.com/spreadsheets/d/1IKAr8A4P0-LhkXqMxizvgYy1E2gph_00M_O0r3rDGkY/edit#gid=0
  --=========================================================================================
}



