name: Package and release

on: [push, pull_request, workflow_dispatch]

jobs:
  lint_code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Install and run luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: --no-color
          annotate: warning

  package_and_release:
    runs-on: ubuntu-latest
    needs: lint_code
    if: ${{ success() && github.ref_type == 'tag' }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        run: ./.github/scripts/generate_changelog.sh
        shell: bash

      - name: Package and release
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

  notify_failures:
    runs-on: ubuntu-latest
    needs: [lint_code, package_and_release]
    if: ${{ always() }}
    steps:
      - name: Send status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          status: ${{ job.status }}
        if: ${{ failure() }}
